package com.datnq.stack.overflow.users.core

class Constants {
    companion object {
        const val EMPTY_STRING = ""
        const val WHITE_SPACE = " "
        const val AT_SIGN = "@"
        const val TOKEN = "anhkhongdoiqua"
        const val DATA = "DATA"
        const val END_CODE_CHECKSUM = "a"
        const val DEFAULT_SERVER_HOST = "vstserver.com"
        const val DEFAULT_SERVER_PORT = "5222"
        const val NEED_UPDATE_DATABASE = 1
        const val NO_NEED_UPDATE_DATABASE = 0
        const val APP_API_FCM_CODE = 7
        const val SERVER_API = "https://vstserver.com/"
        const val URL_CONFIGURE_WIFI = "http://192.168.1.1"
        const val WEATHER_TOKEN = "0249005d78cf5cc7a7d8012de67bec550d245c39"
        const val HEADER_SEND_REQUEST_LOCK_ADDRESS = "%%RQRFD"
        const val HEADER_SEND_RESPONSE_LOCK_ADDRESS = "%%MACDT"
        const val HEADER_SEND_RESPONSE_CARD = "%%RQRFD"
        const val HEADER_CREATE_CARD_REQUEST = "%%CRRFC"
        const val HEADER_CREATE_CARD_RESPONSE = "%%RFREV"
        const val NODE_TYPE_CARD = "WT"
        //region Params key
        const val PARAM_ALERT_TIME = "alert_time"
        const val PARAM_APP_ID = "app_id"
        const val PARAM_AUTHOR_ID = "author_id"
        const val PARAM_BACKUP = "backup"
        const val PARAM_CLIENT_ID = "client_id"
        const val PARAM_CONTENT = "content"
        const val PARAM_CONTEXT_ID = "context_id"
        const val PARAM_DATA = "data"
        const val PARAM_DATA_CODE = "data_code"
        const val PARAM_DEVICE_ID = "device_id"
        const val PARAM_DEVICE_NAME = "device_name"
        const val PARAM_DEVICE_OS = "device_os"
        const val PARAM_DEVICE_TOKEN = "device_token"
        const val PARAM_EVENT_DATA_1 = "event_data1"
        const val PARAM_EVENT_TYPE = "event_type"
        const val PARAM_HOME_ID = "home_id"
        const val PARAM_NODE_ID = "node_id"
        const val PARAM_HOST_ID = "host_id"
        const val PARAM_ID = "id"
        const val PARAM_INDEX = "index"
        const val PARAM_IS_ADMIN = "is_admin"
        const val PARAM_LOCATION = "location"
        const val PARAM_NAME = "name"
        const val PARAM_NEW_PASSWORD = "new_password"
        const val PARAM_OBJECT = "object"
        const val PARAM_OBJECT_NAME = "object_name"
        const val PARAM_OLD_PASSWORD = "old_password"
        const val PARAM_PASSWORD = "password"
        const val PARAM_ROOM_ID = "room_id"
        const val PARAM_SERVER_KEY = "server_key"
        const val PARAM_TAG = "tag"
        const val PARAM_TIME = "time"
        const val PARAM_TITLE = "title"
        const val PARAM_MESSAGE = "message"
        const val PARAM_TOKEN = "token"
        const val PARAM_UPDATE_TYPE = "UpdateType"
        const val PARAM_UPDATE_TYPE_ALL = "All"
        const val PARAM_UPDATE_TYPE_AUTOMATION = "Automation"
        const val PARAM_UPDATE_TYPE_CAMERA = "Camera"
        const val PARAM_UPDATE_TYPE_CLIENT = "Client"
        const val PARAM_UPDATE_TYPE_CONTEXT = "Context"
        const val PARAM_UPDATE_TYPE_DEVICE = "Device"
        const val PARAM_UPDATE_TYPE_DOOR = "Door"
        const val PARAM_UPDATE_TYPE_MOTION = "Motion"
        const val PARAM_UPDATE_TYPE_NODE = "Node"
        const val PARAM_UPDATE_TYPE_PASSWORD = "Password"
        const val PARAM_UPDATE_TYPE_ROOM = "Room"
        const val PARAM_UPDATE_TYPE_SENSOR = "Sensor"
        const val PARAM_UPDATE_TYPE_SENSOR_ALARM = "SensorAlarm"
        const val PARAM_UPDATE_TYPE_SENSOR_TAG = "SensorTag"
        const val PARAM_UPDATE_TYPE_SERVER_NAME = "ServerName"
        const val PARAM_UPDATE_TYPE_SERVER_PASS = "ServerPassword"
        const val PARAM_UPDATE_TYPE_SMART_LOCK = "SmartLock"
        const val PARAM_UPDATE_TYPE_TIMER = "Timer"
        const val PARAM_USER_ID = "user_id"
        const val PARAM_UUID = "uuid"
        const val PARAM_TYPE = "type"
        const val PARAM_CODE = "code"
        const val PARAM_TIME_START = "time_start"
        const val PARAM_TIME_END = "time_end"
        const val PARAM_MOBILE_ID = "mobile_id"
        //endregion

        //region ValueConfigure
        const val PIN_MAX_VALUE = 1600
        const val PIN_MIN_VALUE = 1230
        const val BROADCAST_RECEIVER_HEADER_LOCK_UPDATE = "lockUpdate"
        const val HEADER_RECEIVER_CONFIG_TOUCHPAD_PASS_OK = "%%TPWOK"
        const val HEADER_SEND_CONFIG_TOUCHPAD_PASS_OK_FB = "%%RVTPS"
        const val HEADER_RECEIVE_CONFIG_LOCK_PASS_OK = "%%RPWOK"
        const val HEADER_SEND_CONFIG_LOCK_PASS_OK_FB = "%%RVRPS"
        const val CFG_TYPE_ROLLING_DOOR_CONFIG = "RDP"
        const val WIFI_CONFIG = "WFC"
        const val TOUCHPAD_PASSWORD = "TPW"
        const val LOCK_PASSWORD = "RPW"
        const val ONLY_LOCK_PASSWORD = 1
        const val ONLY_TOUCH_PAD_PASSWORD = 2
        const val TOUCH_PAD_AND_LOCK_PASSWORD = 3
        const val NO_PASSWORD = 4
        const val BROADCAST_RECEIVER_UPDATE_CONNECTION = "connection"
        const val BROADCAST_RECEIVER_CONNECTION_FAIL = "connect_fail"
        const val BROADCAST_RECEIVER_ALERT_DOOR_MOTION_ACTIVE_CONTENT = "alertActive"
        const val BROADCAST_RECEIVER_ALERT_DOOR_MOTION_ACTIVE_CUSTOM = "alertCustom"
        const val SENSOR_MESSAGE = "sensor"
        const val MOTION_MESSAGE = "motion"
        const val DOOR_MESSAGE = "door"
        const val GAS_MESSAGE = "gas"
        const val ALERT_MESSAGE = "alert"
        const val FENCE_MESSAGE = "fence"
        const val UPDATE_UI_MESSAGE = "ui"
        const val BROADCAST_RECEIVER_UPDATE_MOTION = "r_motion"
        const val BROADCAST_RECEIVER_UPDATE_DEVICES = "r_devices"
        const val RECEIVER_ENETWORK_HEADER = "ENetworkReceiverMessage"
        const val SENSOR_TEMPERATURE_TYPE = "00"
        const val SENSOR_HUMIDITY_TYPE = "01"
        const val SENSOR_LIGHT_TYPE = "02"
        const val SENSOR_GAS_TYPE = "03"
        const val TEMPERATURE = 0
        const val HUMIDITY = 1
        const val LIGHT = 2
        const val GAS = 3
        const val MOTION = 5
        const val DOOR = 6
        const val FENCE = 7
        const val HOME_ROOM_ID = "xx"
        const val HEADER_SEND_SETTING = "%%CURAS"
        const val HEADER_SEND_ALARM_MODE_P2 = "%%SALP2"
        const val HEADER_RECEIVER_ALARM_MODE_P2 = "%%ALTP2"
        const val HEADER_RECEIVER_LIGHT_P2 = "%%LDRFB"
        const val HEADER_RECEIVER_LIGHT_BRIGHTNESS = "%%AUSFB"
        const val HEADER_GAS_SAMPLING = "%%FACCA"
        const val HEADER_GAS_SAMPLING_FB = "%%FACFB"
        const val HEADER_LOCK_TOUCH = "%%INLCK"
        const val HEADER_LOCK_TOUCH_FB = "%%LCKFB"
        const val HEADER_GAS_VALUE = "%%AQCON"
        const val HEADER_WHERE = "%%WHERE"
        const val HEADER_PIN_VALUE = "%%STBAT"
        const val HEADER_NODE_INFO = "%%NINFO"
        const val HEADER_DEVICE_FB = "%%DVSFB"
        const val HEADER_SENSOR_FB = "%%SENFB"
        const val HEADER_TIMER_FB = "%%TMRFB"
        const val HEADER_FULL_NODE_FB = "%%PEDFB"
        const val HEADER_DOOR_GATEWAY_FB = "%%STDOO"
        const val HEADER_MOTION_GATEWAY_FB = "%%STPIR"
        const val HEADER_SENSOR_GATEWAY_FB = "%%STENV"
        const val HEADER_SCAN_SENSORTAG = "%%SCNRP"
        const val HEADER_SCAN_SENSORTAG_FB = "%%RVSCN"
        const val HEADER_RGB_COLOR_FB = "%%RGBCL"
        const val HEADER_RGB_EFFECT = "%%RGBEF"
        const val HEADER_RGB_TIMER = "%%LSCHE"
        const val HEADER_FENCE_STATUS = "%%FENCE"
        const val HEADER_FENCE_DETECT = "%%FEDEC"
        const val HEADER_FENCE_FB = "%%REVFD"
        const val HEADER_SET_GATEWAY_ALERT_MODE = "%%SETAL"
        const val HEADER_GATEWAY_ALERT_MODE_STATUS = "%%ALTRI"
        const val HEADER_GATEWAY_ALERT_ON_OFF = "%%ALMMO"
        const val HEADER_RECEIVER_ALERT_SENSOR = "%%BUGAL"
        const val HEADER_SEND_ALERT_SENSOR_FB = "%%REVBA"
        const val HEADER_RECEIVER_DEVICE_CONNECTION = "%%RVAAS"
        const val HEADER_SYNC_MILLIS_TIME = "%%STIML"
        const val HEADER_SEND_TIMER2 = "%%TIME2"
        const val HEADER_SEND_SMART_AIR_TIMER = "%%HVTMR"
        const val HEADER_SEND_AIR_CONDITIONER_TIMER = "%%AIRTM"
        const val HEADER_RECEIVER_SMART_AIR_TIMER_FB = "%%HVTFB"
        const val HEADER_RECEIVER_AIR_CONDITIONER_TIMER_FB = "%%ATMFB"
        const val HEADER_RECEIVER_TIMER2 = "%%TM2FB"
        const val HEADER_RECEIVER_AUTO_CONFIG_OK = "%%AUSOK"
        const val HEADER_SENT_AUTO_OFF = "%%AUOFF"
        const val HEADER_AUTO_OFF_FB = "%%AOSFB"
        const val HEADER_RECEIVER_TOUCH_ERROR = "%%TOFAI"
        const val HEADER_SEND_TOUCH_ERROR_FB = "%%RVTOF"
        const val HEADER_RECEIVER_GATEWAY_ERROR = "%%GWFAI"
        const val HEADER_SEND_GATEWAY_ERROR = "%%RVGWF"
        const val HEADER_START_RGB_LED_MUSIC_EFFECT = "%%RGBMZ"
        const val HEADER_SEND_RESET_NODE = "%%URQTR"
        const val HEADER_RESET_NODE_FB = "%%RVRST"
        const val HEADER_REFRESH_NODE = "%%REFRE"
        const val HEADER_RECEIVER_ROLLING_DOOR_CONFIG_PASSWORD_FB = "%%RDPWD"
        const val HEADER_RECEIVER_ROLLING_DOOR_LOCK_STATUS = "%%RDLST"
        const val HEADER_SEND_ROLLING_DOOR_LOCK_SECURITY = "%%RDLCK"
        const val HEADER_SEND_REQUEST_ROLLING_DOOR_PASSWORD = "%%RQRDP"
        const val HEADER_RECEIVER_REQUEST_ROLLING_DOOR_PASSWORD = "%%RDCPW"
        const val HEADER_ROLLING_DOOR_SENSOR_ERROR = "%%RDLSE" // GOI PHAN HOI LOI CAM BIEN TREN CUA CUON
        const val HEADER_SEND_ROLLING_DOOR_ALARM = "%%SIREN"
        const val HEADER_RECEIVER_EMERSEN_ROLLING_DOOR = "%%RDESW"
        const val HEADER_SEND_ROLLING_DOOR_CONFIG = "%%RDCFG"
        const val HEADER_RECEIVER_ROLLING_DOOR_CONFIG = "%%RDCFB"
        const val HEADER_SEND_ROLLING_DOOR_EMER_CONTEX = "%%RDEME"
        const val HEADER_SEND_ROLLING_DOOR_PANO_ALARM = "%%RDPDA"
        const val HEADER_RECEIVER_ROLLING_DOOR_PANO_ALARM = "%%RDPAF"
        const val HEADER_RECEIVER_ROLLING_DOOR_UPDATE_SETTING_VALUE = "%%RDSFB"
        const val HEADER_SEND_DIMMING_OPTION = "%%RDOTS"
        const val HEADER_RECEIVER_AIR_STATUS = "%%AIRFB"
        const val HEADER_SEND_SMART_AIR_CONTROL = "%%AIRCT"
        const val HEADER_ROLLING_DOOR_ALARM_CONTROL = "%%RDCLW"
        const val HEADER_REQUEST_TIME = "%%RQTML"
        const val ACCOUNT_REQUEST_TIME = "vst.server"
        const val HEADER_NOTIFICATION_XMPP = "%%NOTFN"
        const val HEADER_SEND_IR_LEARN = "%%LEARN"
        const val HEADER_SEND_IR_CONTROL = "%%IROUT"
        const val HEADER_SEND_IR_LEARN_V2 = "%%LEAR2"
        const val HEADER_SEND_IR_CONTROL_V2 = "%%IROU2"
        const val HEADER_RECEIVER_IR_DTA_V2 = "%%ACINF"
        const val HEADER_CHECK_IR_DTA = "%%CKIR2"
        const val HEADER_SEND_ALARM_REPEAT_SETTING = "%%SETOB"
        const val HEADER_RECEIVER_ALARM_REPEAT = "%%OBSTT"
        const val HEADER_ALERT_MODE_INFO = "%%ALMOD"
        const val HEADER_SEND_ALERT_CONFIG = "%%SETAL"
        const val HEADER_SEND_ALERT_FB = "%%REVBA"
        const val HEADER_GAS_ALERT = "%%GAALM"
        const val HEADER_GAS_ALERT_FB = "%%REAAL"
        const val HEADER_SMOKE_ALERT = "%%SMALM"
        const val ALERT_MOTION_YES = "1"
        const val ALERT_DOOR_OPEN = "2"
        const val ALERT_MOTION_OR_DOOR = "3"
        const val ALERT_TOXIC_GAS = "4"
        const val ALERT_SMOKE = "4"
        const val ALERT_TEMPERATURE = "5"
        const val ALERT_ROLLING_DOOR_EMERSENSOR = "6"
        const val ALERT_FENCE = "7"
        const val ALERT_SMART_LOCK = "8"
        const val ALERT_ROLLING_DOOR_CONTROL_WHEN_LOCKING = "9"
        const val HEADER_CHECK = "%%CHECK"
        const val HEADER_SEND_DEVICE_CONTROL = "%%DRIVE"
        const val HEADER_SEND_QUICK_CONTROL = "%%QUICK"
        const val HEADER_SEND_SCAN_SENSORTAG = "%%SCNST"
        const val HEADER_SEND_REQUEST_NODE_INFORMATION = "%%RQTIF"
        const val HEADER_CONFIG_DELETE = "%%DDONE"
        const val HEADER_CONFIG_MOTHER = "MOT"
        const val HEADER_SEND_RGB_COLOR = "%%RGBSC"
        const val HEADER_SEND_CONFIG = "%%CONFG"
        const val HEADER_SEND_RGB_COLOR_DIMMING = "%%RGBEF1"
        const val HEADER_SEND_ALERT_TIMER = "%%ALTMR"
        const val HEADER_RECEIVER_ALERT_TIMER = "%%ALTFB"
        const val HEADER_RECEIVER_ROLLING_DOOR_STATUS = "%%RDSTT"
        const val HEADER_DOOR_STATUS_CLOSED = "0"
        const val HEADER_DOOR_STATUS_OPENED = "1"
        const val HEADER_DOOR_STATUS_INTERMEDIATE = "2"
        const val HEADER_DOOR_STATUS_LOCKING_YES = "1"
        const val HEADER_DOOR_STATUS_LOCKING_NO = "0"
        const val HEADER_DOOR_MOVING_STOP = "0"
        const val HEADER_DOOR_MOVING_UP = "1"
        const val HEADER_DOOR_MOVING_DOWN = "2"
        const val HEADER_SEND_NODE_INFO_FB = "%%REVNI" // - NINFO
        const val HEADER_RECEIVER_SENSOR_CONTEXT_FB = "%%ASCFB"
        const val HEADER_SEND_SENSOR_CONTEXT = "%%ALSCE"
        private const val MS_PER_1_MINUTES = 1000 * 60.toLong()
        const val WAITING_FOR_NODE_CONFIG = MS_PER_1_MINUTES
        const val AUTO_LOCK_ON = 1
        const val AUTO_LOCK_OFF = 0
        const val DEVICE_OFF = 0
        const val DEVICE_ON = 9
        const val MOTOR_LOCK = 1
        const val HEADER_SEND_SET_AUTO_LOCK = "%%AURLK"
        const val HEADER_RECEIVER_SET_AUTO_LOCK_FB = "%%ARLST"
        const val HEADER_SEND_SET_AUTO_LOCK_FBD = "%%Rconst valL"
        const val HEADER_RECEIVER_LOCK_FULL_STATUS = "%%SLSTT"
        const val HEADER_SEND_LOCK_FULL_STATUS_FB = "%%RVSLS"
        const val HEADER_RECEIVER_MOTOR_STATUS = "%%LMOTO"
        const val HEADER_SEND_MOTOR_STATUS_FB = "%%RVLMO"
        const val HEADER_RECEIVER_LOCK_ERROR = "%%INIFW"
        const val HEADER_SEND_LOCK_ERROR_FB = "%%RVINI"
        const val HEADER_RECEIVER_WRONG_TOUCHPAS_PASS = "%%WTPWD"
        const val HEADER_SEND_WRONG_TOUCHPAS_PASS_FB = "%%RVWTP"
        const val HEADER_RECEIVER_DIS_LOCK_5 = "%%DISTP"
        const val HEADER_SEND_DIS_LOCK_5_FB = "%%RVDTP"
        const val HEADER_SEND_REQUEST_TOKEN = "%%RQRTO"
        const val HEADER_RECEIVER_RANDOM_TOKEN = "%%RTOKK"
        const val HEADER_SEND_RANDOM_TOKEN_FB = "%%RVRTO"
        const val HEADER_SEND_UNLOCK = "%%ULOCK"
        const val HEADER_SEND_LOCK = "%%LCKSL"
        const val HEADER_RECEIVER_WRONG_PASS_ONLINE = "%%WRPWD"
        const val HEADER_SEND_WRONG_PASS_ONLINE_FB = "%%RVWRP"
        const val HEADER_RECEIVER_LOCK_CHANGE = "%%LCHAN"
        const val HEADER_SEND_LOCK_CHANGE_FB = "%%RVLCH"
        const val HEADER_RECEIVER_STUCK_LOCK = "%%STUFB"
        const val HEADER_SEND_STUCK_LOCK_FB = "%%RVSTU"
        const val HEADER_SEND_REQUEST_PASS = "%%RQPWD"
        const val HEADER_RECEIVER_PASSWORD = "%%CURPW"
        const val HEADER_SEND_PASSWORD_FB = "%%RVPWD"
        const val HEADER_SEND_SMART_LOCK_LOG_FILE = "%%RQTLF"
        const val HEADER_RECEIVER_SMART_LOCK_LOG_FILE = "%%SLELF"
        const val HEADER_SEND_SETUP_CONTEXT = "%%SETCT"
        const val HEADER_RECEIVE_SETUP_CONTEXT_FB = "%%SCTFB"
        const val LOG_EVENT_CHANGE_REMOTE_PWD = 1
        const val LOG_EVENT_CHANGE_TOUCH_PWD = 2
        const val LOG_EVENT_AUTO_RELOCK_CHANGE = 3
        const val LOG_EVENT_SYSTEM_REBOOT = 4
        const val LOG_EVENT_LOCK_STUCKED = 5
        const val LOG_EVENT_MOTOR_CHANGE_POSITION = 6
        const val LOG_EVENT_PRI_SEC_LOCK_CHANGE = 7
        const val LOG_EVENT_INCORRECT_TOUCH_PWD = 8
        const val LOG_EVENT_INCORRECT_REMOTE_PWD = 9
        const val LOG_EVENT_LOW_BATTERRY = 10
        const val LOG_EVENT_BURGLAR_ALARM_MODE_CHANGE = 11
        const val LOG_EVENT_BURGLAR_DETECTED = 12
        const val LOG_EVENT_USING_MANUAL_KEY = 13
        const val LOG_EVENT_DOOR_CHANGE_STATE = 14
        const val LOG_EVENT_DISABLE_TOUCHPAD = 15
        const val LOG_EVENT_USERS_REQUESTED_SAVED_PWD = 16
        const val LOG_EVENT_USERS_SET_TEMP_TOUCH_PWD = 17
        const val LOG_EVENT_USERS_DELETE_TEMP_TOUCH_PWD = 18
        const val LOG_EVENT_TOUCHPAD_ERROR_OCCURED = 20
        const val LOG_EVENT_CONNECTION_ERROR_OCCURED = 21
        const val LOG_EVENT_NO_REMOTE_PASSWORD = 22
        const val LOG_EVENT_NO_TOUCH_PASSWORD = 23
        const val LOG_MOTOR_UNLOCK_CONTENT = " cửa vừa được mở khoá"
        const val LOG_MOTOR_UNLOCK_CONTENT_1 = " qua thiết bị thông minh"
        const val LOG_MOTOR_UNLOCK_CONTENT_2 = " qua việc nhập mật khẩu trên khoá"
        const val LOG_MOTOR_UNLOCK_CONTENT_3 = EMPTY_STRING
        const val LOG_MOTOR_UNLOCK_CONTENT_4 = " do hệ thống khởi động lại"
        const val LOCK_LOG_TITLE = "Khoá ở "
        const val LOCK_INIFW_MESSAGE_1 = " không khởi tạo được mật khẩu trên bàn phím cảm ứng "
        const val LOCK_INIFW_MESSAGE_2 = " không khởi tạo được mật khẩu điều khiển qua thiết bị thông minh "
        const val LOCK_INIFW_MESSAGE_3 = " không khởi tạo được mật khẩu"
        const val TYPE_STAMP_TICK = 0
        const val ENTER_PASSWORD_DISABLE = 0
        const val ENTER_PASSWORD_ENABLE = 1
        const val LOCK_OPEN = 0
        const val ALERT_DELAY_TIMER = 1000 * 10.toLong()
        const val OK = 1
        const val HEADER_LMKEY = "%%LMKEY" // Thong bao khoa mo bang chia
        const val HEADER_LMKEY_FB = "%%RVSMK"
        val USER_LOCK = arrayOf("Khách thuê phòng ", "Người quen ", "Nhân viên quản lý ", "Nhân viên vệ sinh ")
        const val ALERT_LOCK_LOW_BATTERY = 13
        const val ALERT_LOCK_WRONG_TOUCH_PASS = 14
        const val ALERT_LOCK_TOUCH_PASS_DISABLE = 15
        const val ALERT_LOCK_STUFB_MESSAGE = 16
        const val ALERT_LOCK_TOUCHPAD_ERROR = 17
        const val ALERT_LOCK_NO_CONNECTION = 18
        const val TIME_ZONE = "GMT+7"
        const val MASTER = "vst.smartlock"
        const val MASTER_MESSAGE_HEADER = "%%ECHOS@"
        const val MASTER_RECEIVER_MESSAGE_HEADER = "%%ECHOS@"
        const val SYNC_TEMP_KEY = "SYNC_TEMP_KEY!"
        const val ALARM_AUTHOR_LOGIN_REQUEST = "ALARM_AUTHOR_LOGIN_REQUEST"
        const val HEADER_SEND_REQUEST_LIST_TEMP_PASSWORD = "%%TPWRQ"
        const val HEADER_RECEIVER_LIST_TEMP_PASSWORD = "%%TPWFB"
        const val HEADER_DELETE_TEMP_PASS = "%%DTTPW"
        const val HEADER_DELETE_TEMP_PASS_FB = "%%TTPDE"
        const val HEADER_TEMP_PASSWORD_FB = "%%TTPCO"
        const val HEADER_SMARTLOCK_CONTROL_ERROR = "%%RMERR"
        const val HEADER_SMARTLOCK_LOW_BARRERY = "%%LOWBA"
        const val HEADER_SMARTLOCK_PIN_VALUE = "%%SLBAT"
        const val HEADER_NEW_PASS = "%%STTPW"
        const val HEADER_RECEIVER_TOUCHPAD_ERROR = "%%TPERR"
        const val HEADER_RECEIVER_LOCK_NOT_CONNECT = "%%ECONN"
        //endregion

        //region Value define
        const val SMART_LOCK_PASS = "12345678"
        const val SMART_LOCK_TOUCH_PASS = "133784"
        const val APP_DATABASE_NAME = "VST_HOTEL_2020"
        const val MOTION_NOT_ACTIVE = 0
        const val MOTION_ACTIVE = 1
        const val ALERT_ON = 1
        const val ALERT_OFF = 0
        const val MOTION_YES = 1
        const val MOTION_NO = 0
        const val DOOR_OPEN = 1
        const val BLIND_OPEN = 2
        const val BLIND_CLOSE = 0
        const val ROOM_TYPE_LIVING_ROOM = 0
        const val ROOM_TYPE_BED_ROOM = 1
        const val ROOM_TYPE_KITCHEN = 2
        const val ROOM_TYPE_OUTSIDE = 3
        const val ROOM_TYPE_BATH_ROOM = 4
        const val ROOM_TYPE_DRESSING_ROOM = 5
        const val ROOM_TYPE_GARAGE = 6
        const val CHANGE_ROOM_RESULT = 1
        const val DEVICE_LIGHT = 0
        const val DEVICE_FAN = 1
        const val DEVICE_TIVI = 2
        const val DEVICE_AIR_CONDITIONER = 3
        const val DEVICE_LAMP = 4
        const val DEVICE_LIGHT_COLOR = 5
        const val DEVICE_LIGHT_GARDEN = 6
        const val DEVICE_PUMP = 7
        const val DEVICE_OUTLET = 8
        const val DEVICE_BLIND = 9
        const val DEVICE_OTHER = 10
        const val DEVICE_ALARM = 11
        const val DEVICE_FENCE = 12
        const val DEVICE_ROLLING_DOOR = 13
        const val DEVICE_SMART_LOCK = 14
        const val DEVICE_SMART_AIR = 15
        const val DEVICE_AIR_CONDITIONER_2 = 16
        const val TYPE_CONTROL_AIR_CONDITIONER_AUTO = 49
        const val NODE_TYPE_GATEWAY_0 = "G0"
        const val NODE_TYPE_GATEWAY_1 = "G1"
        const val NODE_TYPE_GATEWAY_2 = "G2"
        const val NODE_TYPE_GATEWAY_3 = "G3"
        const val NODE_TYPE_GATEWAY_S = "GS"
        const val NODE_TYPE_GATEWAY_B = "GB" // GW LOA - HANG RAO GB
        const val NODE_TYPE_GATEWAY_L = "GL" // GW KHOA - LOA - HANG RAO
        const val NODE_TYPE_GATEWAY_E = "GE" // GW TICH HOP SENSOR
        const val NODE_TYPE_GATEWAY_P = "GP" // GW TICH HOP MOTION
        const val NODE_TYPE_GATEWAY_R = "GR" // GW TICH KET NOI CUA CUON
        const val NODE_TYPE_GATEWAY_P2 = "P2" // GW TICH HOP CAM BIEN NOI DAY
        const val NODE_TYPE_LOCK = "WL"
        const val NODE_TYPE_ROLLING_DOOR = "RD"
        const val NODE_TYPE_GAS = "S0"
        const val NODE_TYPE_SMOKE = "S1"
        const val NODE_TYPE_DOOR = "S4"
        const val NODE_TYPE_MOTION = "S2"
        const val NODE_TYPE_SENSOR = "S3"
        const val NODE_TYPE_IR = "I0"
        const val NODE_TYPE_IR_2 = "I2"
        const val NODE_TYPE_SMART_AIR = "A0"
        const val NODE_TYPE_DEVICE_1 = "D1"
        const val NODE_TYPE_DEVICE_2 = "D2"
        const val NODE_TYPE_DEVICE_3 = "D3"
        const val NODE_TYPE_DEVICE_4 = "D4"
        const val NODE_TYPE_DEVICE_8 = "D8"
        const val NODE_TYPE_COLOR_LED = "L0"
        const val NODE_TYPE_DEVICE_DIMMING_A1 = "A1"
        const val NODE_TYPE_DEVICE_DIMMING_Z1 = "Z1"
        const val NODE_TYPE_PUMP = "PU"
        const val NODE_TYPE_POWER = "P0"
        const val NODE_TYPE_MEDIA = "M0"
        const val NODE_TYPE_BLIND = "B0"
        const val TYPE_OPTION_SENSOR = "sensor"
        const val TYPE_OPTION_DOOR = "door"
        const val TYPE_OPTION_MOTION = "motion"
        private const val NOT_OK = 0

        // encode backup database
        const val ENCODE_LOCAL = NOT_OK

        // adapter ODeviceContest
        const val STATUS_DO_NOT_CARE = 2
        const val STATUS_ON = 1
        const val STATUS_OFF = 0
        const val TEMP_CLIENT_NAME = "xxx"
        const val CHECK_STATUS = "%%CHECK"
        const val IMAGE_RESIZE_FOLDER = "/VSTRETAIL/"
        const val URL_DOOR_INFO = "http://www.vsmarttek.vn/san-pham/vsmarttek-STD.17.2R"
        const val URL_MOTION_INFO = "http://www.vsmarttek.vn/san-pham/vsmarttek-STP.17.2R"
        const val URL_SENSOR_INFO = "http://www.vsmarttek.vn/san-pham/vsmarttek-STE.17.2R"
        const val CAMERA_PRODUCER_EYE_SIGHT = "EYESIGHT"
        const val CAMERA_PRODUCER_KBVISION = "KBVISION"
        const val CAMERA_PRODUCER_QUESTEK = "QUESTEK"
        const val CAMERA_PRODUCER_GOLDEYE = "GOLDEYE"
        const val CAMERA_PRODUCER_YOUSEE = "YOUSEE"
        const val CAMERA_PRODUCER_UNV = "UNV"
        const val CAMERA_PRODUCER_HIKVISION = "HIKVISION"
        const val STK_TYPE_NOT_DETERMINE = 0
        const val STK_TYPE_FENCE = 0
        const val STK_TYPE_DOOR = 1
        const val STK_TYPE_MOTION = 2
        const val STK_TYPE_SENSOR = 3
        const val STK_TYPE_LOCK = 4
        const val ROLLING_DOOR_SUCCEEDED = 0
        const val ROLLING_DOOR_SYNTAX_ERR = 1
        const val ROLLING_DOOR_DATA_ERR = 2
        const val ROLLING_DOOR_ADDRESS_ERR = 3
        const val ROLLING_DOOR_PASSWORD_ERR = 4
        const val ROLLING_DOOR_STORAGE_ERR = 5
        const val NOTIFICATION_TYPE_ROLLING_DOOR = 1
        const val NOTIFICATION_TYPE_ROLLING_ALARM = 2
        const val CODE_CONTROL_LOGFILE = "AA"
        const val TYPE_CONTROL_LOGFILE_OFF = 0 // TAT
        const val TYPE_CONTROL_LOGFILE_ON = 1 // BAT
        const val TYPE_CONTROL_LOGFILE_CLOSE = 2 // DONG
        const val TYPE_CONTROL_LOGFILE_OPEN = 3 // MO
        const val TYPE_CONTROL_LOGFILE_LOCK_TOUCH = 4 // KHOA CAM UNG
        const val TYPE_CONTROL_LOGFILE_UNLOCK_TOUCH = 5 // MO KHOA CAM UNG
        const val TYPE_CONTROL_LOGFILE_DEVICE_TIMER_ON = 6 // BAT HEN GIO
        const val TYPE_CONTROL_LOGFILE_DEVICE_TIMER_OFF = 7 // TAT HEN GIO
        const val TYPE_CONTROL_LOGFILE_ALARM_ON = 8 // BAT CHONG TROM
        const val TYPE_CONTROL_LOGFILE_ALARM_OFF = 9 // TAT CHONG TROM
        const val TYPE_CONTROL_LOGFILE_ALARM_TIMER_ON = 10 // BAT HEN GIO CHONG TROM
        const val TYPE_CONTROL_LOGFILE_ALARM_TIMER_OFF = 11 // TAT HEN GIO CHONG TROM
        const val TYPE_CONTROL_LOGFILE_ALARM_SETTING = 12 // TUY CHINH CAM BIEN BAO DONG
        const val TYPE_CONTROL_LOGFILE_CONTEXT_CREATE = 13 // TAO NGU CANH
        const val TYPE_CONTROL_LOGFILE_CONTEXT_DELETE = 14 // XOA NGU CANH
        const val TYPE_CONTROL_LOGFILE_CONTEXT_ON = 15 // BAT NGU CANH
        const val TYPE_CONTROL_LOGFILE_AUTHOR_CREATE = 16 // KHOI TAO PHAN QUYEN
        const val TYPE_CONTROL_LOGFILE_AUTHOR_DELETE = 17 // XOA PHAN QUYEN
        const val TYPE_CONTROL_LOGFILE_AUTHOR_APPROVE = 18 // CHAP THUAN PHAN QUYEN
        const val TYPE_CONTROL_LOGFILE_BACKUP_DATA = 19 // LUU TRU DU LIEU
        const val TYPE_CONTROL_LOGFILE_SYSNC_DATA = 20 // DONG BO DU LIEU
        const val TYPE_CONTROL_LOGFILE_AUTO_OFF_TRUE = 21 // BAT CHE DO TU DONG TAT
        const val TYPE_CONTROL_LOGFILE_AUTO_OFF_FALSE = 22 // TAT CHE DO TU DONG TAT
        const val TYPE_CONTROL_LOGFILE_LINK_CONTEXT = 23 // LIEN KET NGU CANH
        const val TYPE_CONTROL_LOGFILE_ALARM_CONTEXT_ON = 24 // BAT NGU CANH BAO DONG
        const val TYPE_CONTROL_LOGFILE_ALARM_CONTEXT_OFF = 25 // TAT NGU CANH BAO DONG
        const val TYPE_CONTROL_LOGFILE_VIEW_IMAGE_ALARM = 26 // XEM ANH BAO DONG
        const val TYPE_CONTROL_LOGFILE_CONTROL = 27 // DIEU KHIEN
        const val TYPE_CONTROL_LOGFILE_PAUSE = 28 // DUNG
        const val TYPE_CONTROL_LOGFILE_CHANGE_COLOR = 29 // THAY DOI MAU SAC
        const val TYPE_CONTROL_LOGFILE_CHANGE_BRIGHTNESS = 30 // THAY DOI DO SANG
        const val TYPE_CONTROL_LOGFILE_ALARM_ON_2 = 31 // BAT BAO DONG KEM LOA
        const val TYPE_CONTROL_ROLLING_DOOR_LOCK = 32 // BAT KHOA AN TOAN
        const val TYPE_CONTROL_ROLLING_DOOR_UNLOCK = 33 // TAT KHOA AN TOAN
        const val TYPE_CONTROL_ROLLING_DOOR_TIMER_ON = 34 // BAT HEN GIO KHOA AN TOAN
        const val TYPE_CONTROL_ROLLING_DOOR_TIMER_OFF = 35 // TAT HEN GIO KHOA AN TOAN
        const val TYPE_CONTROL_ROLLING_DOOR_CHANGE_PASS = 36 // DOI MAT KHAU KHOA AN TOAN
        const val TYPE_CONTROL_ROLLING_DOOR_VIEW_LOG = 37 // XEM LICH SU DIEU KHIEN
        const val TYPE_CONTROL_ROLLING_PASSWORD_WRONG = 38 // NHAP SAI MAT KHAU KHOA AN TOAN CUA CUON
        const val TYPE_CONTROL_ROLLING_LOCKED = 39 // BI KHOA DIEU KHIEN THIET BI TRONG 5 PHUT
        const val TYPE_CONTROL_SMART_LOCK_LOCKED = 40 // VUA KHOA
        const val TYPE_CONTROL_SMART_LOCK_UNLOCKED = 41 // VUA MO KHOA
        const val TYPE_CONTROL_SMART_LOCK_VIEW_LOGFILE = 42 // XEM LICH SU DIEU KHIEN
        const val TYPE_CONTROL_SMART_LOCK_CHANGE_APP_PASS = 43 // DOI MAT KHAU TREN PHAN MEM
        const val TYPE_CONTROL_SMART_LOCK_CHANGE_TOUCHPAD_PASS = 44 // DOI MAT KHAU TREN BAN PHIM CAM UNG
        const val TYPE_CONTROL_SMART_LOCK_AUTO_LOCK_ON = 45 // BAT CHE DO TU DONG KHOA
        const val TYPE_CONTROL_SMART_LOCK_AUTO_LOCK_OFF = 46 // TAT CHE DO TU DONG KHOA
        const val TYPE_CONTROL_SMART_LOCK_UPDATED = 47 // THEM/SUA KHOA PHU
        const val TYPE_CONTROL_SMART_LOCK_DELETED = 48 // XOA KHOA
        const val TYPE_CONTROL_CHANGE_PASSWORD = 50 // DOI MAT KHAU
        //endregion
    }
}